language: bash
sudo: required
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python-pip libffi-dev libssl-dev
  - sudo pip install pyopenssl ndg-httpsclient pyasn1 awscli
script:
  - make test ENV=cloud