development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB'] %>
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: <%= ENV['DB'] %>
  
production:
  <<: *default
  database: <%= ENV['DB'] %>
