db:
  image: postgres
  ports:
    - "5432"
web:
  #image: dcrbsltd/hellorails_web
  build: web
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/hellorails
  ports:
    - "80:3000"
  links:
    - db
