development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: hellorails_test
  
production:
  <<: *default
  database: hellorails_production
